export const ProjectObjOne = {
  imgOne: require("../../images/bot.png").default,
  altOne: "bot_browse",
  imgThree: require("../../images/under-construction.jpg").default,
  altThree: "under-construction",
  imgTwo: require("../../images/yourplaces.png").default,
  altTwo: "yourplaces",
  buttonLabelOne: "React-JS",
  buttonLabelTwo: "Redux",
  buttonLabelThree: "Node-JS & Express",
  buttonLabelFour: "MONGO-DB",
  buttonLabelFive: "JavaScript",
  buttonLabelSix: "HTML",
  buttonLabelSeven: "CSS",
  buttonLabelEight: "Python",
  buttonLabelNine: "Java",
};
