export const homeObjOne = {
  id: " education",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Education",
  imgStart: false,
  imgOne: require("../../images/SCE_logo.png").default,
  imgTwo: require("../../images/SQL_logo.png").default,
  imgThree: require("../../images/udemy-logo.png").default,
  altOne: "sce_logo",
  altTwo: "SQL_logo",
  altThree: "udemy_logo",
  dark: true,
  primary: true,
  darkText: false,
};
