export const homeObjOne = {
  id: " education",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Education",
  headlineOne: "SCE-Shamoon college of engineering 2016-2020",
  headlineTwo: "React & Redux Course (40Hours) by SQLink",
  imgStart: false,
  imgOne: require("../../images/SCE_logo.png").default,
  imgTwo: require("../../images/SQL_logo.png").default,
  altOne: "sce_logo",
  altTwo: "SQL_logo",
  dark: true,
  primary: true,
  darkText: false,
  buttonLabelOne: "React-JS",
  buttonLabelTwo: "Redux",
  buttonLabelThree: "Node-JS",
  buttonLabelFour: "MONGO-DB",
  buttonLabelFive: "JavaScript",
  buttonLabelSix: "HTML",
  buttonLabelSeven: "CSS",
  buttonLabelEight: "Python",
  buttonLabelNine: "Java",
};
