export const homeObjOne = {
  id: " about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Education",
  headlineOne: "SCE-Shamoon college of engineering 2016-2020",
  headlineTwo: "React & Redux Course (40Hours) by SQLink",
  imgStart: false,
  imgOne: require("../../images/SCE_logo.png").default,
  imgTwo: require("../../images/SQL_logo.png").default,
  altOne: "sce_logo",
  altTwo: "SQL_logo",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: " education",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Skills",
  headline: "B.sc Software Engineer at SCE",
  description: " React & Redux Course (40 hours)",
  buttonLabel: "Learn more",
  imgStart: false,
  //img: require("../../images/svg-2.svg").default,
  alt: "Piggybank",
  dark: false,
  primary: false,
  darkText: true,
};
